# Generated by Django 3.1.7 on 2021-03-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(default=512, max_length=255, verbose_name='Оперативная память'),
            preserve_default=False,
        ),
    ]
